/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 19 18:15:13 GMT 2024
 */

package com.example.triangle;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.triangle.Triangle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Triangle_ESTest extends Triangle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = Triangle.classifyTriangle(2822, 2, 2822);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = Triangle.classifyTriangle(3246, 2798, 2798);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = Triangle.classifyTriangle(2213, 1445, 778);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = Triangle.classifyTriangle(1, 1, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Triangle triangle0 = new Triangle();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = Triangle.classifyTriangle(963, 963, 963);
      assertEquals(2, int0);
  }
}
