/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 17 10:53:23 GMT 2024
 */

package com.example.sortcocktail;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.sortcocktail.SortCocktail;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SortCocktail_ESTest extends SortCocktail_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer[] integerArray0 = new Integer[9];
      Integer integer0 = new Integer(2707);
      integerArray0[0] = integer0;
      Integer integer1 = new Integer((-715));
      integerArray0[1] = integer1;
      Integer integer2 = new Integer((int) integerArray0[1]);
      integerArray0[2] = integer2;
      integerArray0[3] = integer0;
      integerArray0[4] = integerArray0[2];
      Integer integer3 = new Integer(5);
      Integer[] integerArray1 = SortCocktail.sort(integerArray0, integer3);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer[] integerArray0 = new Integer[9];
      Integer integer0 = new Integer(2707);
      integerArray0[0] = integer0;
      Integer integer1 = new Integer((-715));
      integerArray0[1] = integer1;
      Integer integer2 = new Integer(2);
      Integer[] integerArray1 = SortCocktail.sort(integerArray0, integer2);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SortCocktail sortCocktail0 = new SortCocktail();
  }
}
