/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 17 11:00:21 GMT 2024
 */

package com.example.sortcocktail;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.sortcocktail.SortCocktail;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SortCocktail_ESTest extends SortCocktail_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer[] integerArray0 = new Integer[6];
      Integer integer0 = new Integer(3463);
      integerArray0[0] = integer0;
      integerArray0[1] = integerArray0[0];
      Integer integer1 = new Integer(728);
      integerArray0[2] = integer1;
      int int0 = 3;
      Integer[] integerArray1 = SortCocktail.sort(integerArray0, (Integer) int0);
      assertEquals(6, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer[] integerArray0 = new Integer[6];
      Integer integer0 = new Integer(3463);
      integerArray0[0] = integer0;
      Integer integer1 = new Integer(1094);
      integerArray0[1] = integer1;
      integerArray0[2] = integer1;
      int int0 = 3;
      Integer[] integerArray1 = SortCocktail.sort(integerArray0, (Integer) int0);
      assertSame(integerArray0, integerArray1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SortCocktail sortCocktail0 = new SortCocktail();
  }
}
