/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 19 18:23:28 GMT 2024
 */

package com.example.triangle;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.triangle.Triangle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Triangle_ESTest extends Triangle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Triangle triangle0 = new Triangle();
      Triangle.classifyTriangle(1440, 1440, 1440);
      Triangle.classifyTriangle((-3917), (-3917), 0);
      Triangle.classifyTriangle(817, 0, (-272));
      Triangle.classifyTriangle(1072, 1072, 723);
      Triangle.classifyTriangle(642, 377, 377);
      Triangle.classifyTriangle(0, (-1), 2620);
      Triangle.classifyTriangle(4746, 563, 563);
      Triangle.classifyTriangle(4746, 0, (-1151));
      Triangle.classifyTriangle(0, 4746, 2620);
      Triangle.classifyTriangle(1, 1, 642);
      Triangle.classifyTriangle((-1151), 3, (-4610));
      Triangle.classifyTriangle(0, 0, 3485);
      Triangle.classifyTriangle(0, 0, 0);
      Triangle.classifyTriangle(2, (-4610), (-1));
      Triangle.classifyTriangle(4746, 3825, 1692);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Triangle.classifyTriangle(0, 0, 0);
      Triangle triangle0 = new Triangle();
      Triangle.classifyTriangle(0, 0, 0);
      Triangle.classifyTriangle(0, 0, (-1341));
      Triangle.classifyTriangle(0, 0, 3732);
      Triangle.classifyTriangle(0, (-887), 0);
      Triangle.classifyTriangle((-923), 0, 0);
      Triangle.classifyTriangle(0, 0, 0);
      Triangle.classifyTriangle((-1783), 0, 0);
      Triangle.classifyTriangle(3112, (-1783), 0);
      Triangle.classifyTriangle(3732, (-1007), 0);
      Triangle.classifyTriangle(0, (-923), (-1023));
      Triangle.classifyTriangle(0, 2699, 3112);
      Triangle.classifyTriangle(0, 0, (-887));
      Triangle.classifyTriangle((-1), 1003, 0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Triangle.classifyTriangle(0, 0, 1550);
      Triangle triangle0 = new Triangle();
      Triangle.classifyTriangle((-2604), 457, (-2604));
      Triangle.classifyTriangle(0, 0, (-5));
      Triangle.classifyTriangle(0, (-1), (-1));
      Triangle.classifyTriangle(0, 0, 0);
      Triangle.classifyTriangle(0, 0, 0);
      Triangle.classifyTriangle(0, 0, (-5));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Triangle triangle0 = new Triangle();
      Triangle.classifyTriangle(0, (-2381), 0);
      Triangle.classifyTriangle(190, 0, 0);
      Triangle.classifyTriangle(0, 0, 0);
      Triangle.classifyTriangle(0, 0, 782);
      Triangle.classifyTriangle((-2858), (-2858), (-2858));
      Triangle.classifyTriangle(0, 2794, 0);
      int int0 = Triangle.classifyTriangle((-4327), (-1751), 2794);
      assertEquals(0, int0);
      
      Triangle.classifyTriangle(2794, (-1751), 0);
      int int1 = Triangle.classifyTriangle(468, 0, 1);
      Triangle.classifyTriangle(0, 0, (-1751));
      int int2 = Triangle.classifyTriangle(7, 0, 1157);
      int int3 = Triangle.classifyTriangle(0, 0, 0);
      assertTrue(int3 == int1);
      
      int int4 = Triangle.classifyTriangle(0, 0, (-451));
      assertTrue(int4 == int2);
      
      int int5 = Triangle.classifyTriangle((-2858), 0, 0);
      assertEquals(0, int5);
  }
}
